(function(z){
var mL=function(a,b,c){b="new"===(b||a.kd);return c?(a=a.d.u.v().get(z.U.yp),b?-1:-a):a.Zk+(b?-1:1)};var nL=function(a){z.Pv.call(this,a);this.Zk=0;this.kd="new"};var oL=function(a,b){a.xX=b};
var pL=function(a){return(0,z.Q)('\x3cdiv class\x3d"fyre '+(a.Fd?"fyre-liveblog ":"")+(a.$g?"fyre-livechat ":"")+(a.UT?"fyre-bootstrap ":"")+(a.oe?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Sa?"fyre-avatar-disabled":"")+'"\x3e'+(a.sv?z.Fo(z.Qs(a)):"")+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Sa?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.io?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var qL=function(a){return(0,z.Q)('\x3ca href\x3d"'+z.R(z.S(a.Ea))+'" title\x3d"'+z.R(a.aa)+'" data-id\x3d"'+z.R(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.R(a.CT)+'"\x3e\x3cimg src\x3d"'+z.R(z.S(a.wd))+'" alt\x3d"'+z.R(a.aa)+'" onerror\x3d"javascript:this.src\x3d\''+z.R(z.Zo(a.$b))+"';\" /\x3e\x3c/a\x3e")};
var rL=function(a){return(0,z.Q)(z.$q(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.P(a.j.$N)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(a.j.Rx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(a.j.Po)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(a.j.Sx)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var sL=function(a){return(0,z.Q)('\x3cdiv class\x3d"tooltip"\x3e'+z.P(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var tL=function(){};var uL=function(a){this.uG=!1;this.Eo=[];this.yb=null;z.Gf.call(this,a)};var vL=function(a,b){z.Kj.call(this,b,a)};var wL=function(a,b){z.fG.call(this,a,b)};
var xL=function(a,b){var c=a.d.Ib;c.mh[4]&&(z.oz(c,4,(0,z.r)(function(a){b.e(a,"threadBreakout",this.Fr)},a)),z.qz(c,4,(0,z.r)(function(a){b.Ia(a,"threadBreakout",this.Fr)})))};var yL=function(a,b){var c=[a.jm,a.kz];a.ug&&c.push(a.ug);a.kt&&c.push(a.kt);a.lz&&c.push(a.lz);z.w(c,function(a){z.ok(a,"fyre-stream-sort-selected")});z.mk(b,"fyre-stream-sort-selected")};var zL=function(a,b){z.fG.call(this,a,b)};
var AL=function(a,b){z.Rx.call(this,a,b);this.Zg=!1;this.EI=!!this.D.J.xG;this.Ga=new z.$x;this.Ga.qc(this);this.hu="archiveShowMore"};var BL=function(a,b){z.cG.call(this,a,b)};var CL=function(a,b,c){z.fu.call(this,a,b,c);this.Gz=b||"";this.rg(sL(this.s()))};var DL=function(a,b,c){z.$t.call(this,a,b||3,c)};var EL=function(a,b){z.T.call(this,b);this.l=a};var FL=function(a,b){z.T.call(this,b);this.Ac=a};var GL=function(a,b){FL.call(this,a,b)};
var HL=function(){var a=z.t.window,b=z.t.document;function c(){var a=A.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){A.bX||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(A,g)}function f(a){var b;if(a.jP)return a;if(A.aX&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.jP=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.PT&&a.PT("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var A={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.aX,shivMethods:!1!==g.bX,type:"default",shivDocument:f};f(b)};var IL=function(a,b){z.nG.call(this,a,b);a.J.cP||HL();var c=a.u.zc(),d=a.u.v();this.gi=new z.dG(a,a.Ll.Da,d.$g()||z.eg);this.F(this.gi);a.J.Sa||(this.zn=new GL(c),this.F(this.zn));this.Nr=new z.bG;this.F(this.Nr)};var JL=function(a){var b=z.E.ib()||z.E.get(z.D.Ap);return!a.w.Fd()||b};var KL=function(a){z.xz.call(this,a);this.Qm=1};
var LL=function(a){z.Ts.call(this,a);z.rv(a.u);this.Rb=new IL(a);this.Tq.start();this.Bl(this.Rb);z.Ys(this)};var ML=function(a,b){this.UC=vL;this.IJ=LL;z.X.To(b.strings||{});z.Pn.call(this,a,b)};var NL=function(a){a.ok&&(a.ok.p(),delete a.ok)};z.u(nL,z.Pv);z.e=nL.prototype;z.e.ml=z.l(60);z.e.vF=z.l(62);z.e.wF=z.l(61);z.e.vF=z.L(62,function(a){this.Ka||(this.Ao[a]=!1,z.Qv(this,a,function(a){a.N(a.xa.Pm)}))});
z.e.wF=z.L(61,function(a,b){if(!this.Ka){var c=this.d.u.v(),d=z.Mu(a,b),f=c.get(z.U.Ft);c.set(z.U.yp,d.gV);z.x(d.$a,(0,z.r)(this.d.U.N,this.d.U,"bootstrap_author_received"));d.content=z.mj(d.content,function(a,b){return!z.Ta(f,b)});z.x(d.content,function(a){z.lb(d.content,z.Sv(this,a))},this);z.lb(this.pc,z.lj(d.content,z.Db(a)));this.Yd(a,d.content);z.Qv(this,a,function(b){b.N(b.xa.Ek,{Id:a});b.set(b.k.kf,!0)})}});
z.e.ml=z.L(60,function(a,b){this.Zk=a;this.kd=b||this.kd;var c=this.Jd[a]=new z.Lv;z.hv.C();var d=this.d.u.v(),f=(0,z.r)(this.wF,this,a),g=(0,z.r)(this.vF,this,a),h=this.d.J.Vm,d=d.get(z.U.Hc),h=z.v.Lu(d,h)+String(a)+".json";z.iv(0,h,f,g);return c});z.JG.prototype.ml=z.L(59,function(a,b){this.Nk||(this.Nk=new nL(this.D));var c=this.Nk,d=mL(c,a,b);return c.ml(d,a)});z.hv.prototype.Ph=z.L(51,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.v.L.xd,z.v.gf,a.na);(new z.Qe({url:a,wa:b,sa:c})).send()});
z.fw.prototype.Ph=z.L(50,function(a){var b={na:this.d.u.v().id},c=z.hv.C().Ph;z.gw(this,c,b,a);return a});z.JG.prototype.Ph=z.L(49,function(){z.lw(this);this.Hi=new z.fw(this.D,void 0);var a=new z.Lv;this.Hi.Ph(a);return a});z.hv.prototype.Lh=z.L(48,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.v.L.xd,z.v.gf,a.na,a.UN);(new z.Qe({url:a,wa:b,sa:c})).send({format:"stream"})});z.fw.prototype.Lh=z.L(47,function(a,b){var c={na:this.d.u.v().id,UN:a},d=z.hv.C().Lh;z.gw(this,d,c,b);return b});
z.JG.prototype.Lh=z.L(46,function(a){z.lw(this);this.Hi=new z.fw(this.D,void 0);var b=new z.Lv;this.Hi.Lh(a,b);return b});z.T.prototype.JG=z.L(45,function(){return this.Y});z.Hj.prototype.io=z.L(44,function(){return this.get(this.k.xp)});z.u(tL,z.Vn);z.ca(tL);var OL={zY:"attachmentDelegate"};z.lb(OL,z.$G);tL.prototype.eo=function(a){var b=tL.b.eo.call(this,a),c=a.attachmentDelegate;c&&(b.bO=c);b.Lx=a[OL.ML]||null;return b};z.u(uL,z.Gf);uL.prototype.qU=function(a){this.yb||(this.yb=z.t.setInterval((0,z.r)(this.iQ,this),5E3));this.Eo=this.Eo.concat(a)};
uL.prototype.iQ=function(){this.Eo.length&&(this.uG||(z.vc("//platform.twitter.com/impressions.js"),this.uG=!0),z.t.twttr=function(){var a=z.t.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.t.twttr.impressions.ready((0,z.r)(function(a){a.impressions.logTweets(this.Eo,{partner:"livefyre"});this.Eo=[]},this)))};uL.prototype.p=function(){(0,window.clearInterval)(this.yb);uL.b.p.call(this)};z.u(vL,z.Kj);vL.prototype.Wy=function(a){this.Ci=new z.cv(this);this.su=new z.Qq(this,a);this.Jc=new z.Bi(this);this.cb=new z.Av(this,a);this.Ll=new z.Hv(this);this.u=new z.pv(this,a);this.Lb=new z.JG(this,a);new z.rf;this.Wo=new z.zw(this,a);this.sz=new z.mw(this);this.RX=new uL(this);this.Ib=new z.ez(this)};z.u(wL,z.fG);z.e=wL.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.Gx=b.v().Fd();a.dV=!z.E.get(z.E.k.Td);a.Ed=b.Ed(z.E.id);a.fP=2===c.get(z.U.Wi);a.eP=3===c.get(z.U.Wi);a.j={jU:z.X.get(z.X.g.Xt),mU:z.X.get(z.X.g.Yt),AT:z.X.get(z.X.g.ZA),Rx:z.X.get(z.X.g.Rp),Sx:z.X.get(z.X.g.Sp),Po:z.X.get(z.X.g.aC),fp:z.X.get(z.X.g.Xp),LX:z.X.get(z.X.g.sC)};return a};
z.e.K=function(a){wL.b.K.call(this,a);a=this.c;var b;b=this.s();var c=z.Q,d=z.$q(b),f;f=b.Gx?(0,z.Q)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.dV?b.Ed?z.P(b.j.mU):z.P(b.j.jU):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(b.j.Rx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Po)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(b.j.Sx)+"\x3c/a\x3e"+(b.fP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Po)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.P(b.j.LX)+"\x3c/a\x3e":"")+(b.eP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Po)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.P(b.j.AT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.ll=this.n("fyre-follow-conversation");this.kt=this.n("fyre-stream-sort-hot-threads")||
null;this.lz=this.n("fyre-stream-sort-top-comments")||null;this.ug=this.n("fyre-stream-sort-back");this.jm=this.n("fyre-stream-sort-newest");this.kz=this.n("fyre-stream-sort-oldest");this.JI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Dd()};z.e.m=function(){wL.b.m.call(this);var a=this.q();z.E.on(z.E.xa.Pf,this.Yn,this);a.e(this.c,"click",this.hb);z.w([3,4,5],function(b){z.gG(this,a,b)},this);xL(this,a)};
z.e.hb=function(a){a.preventDefault();a=a.target;if(!z.sk(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.ug)if(a===this.ll)this.tF();else switch(yL(this,a),this.im(),a){case this.kt:this.fE();break;case this.lz:this.dispatchEvent({type:"sortTopComments",Wb:(0,z.r)(this.Dd,this)});break;case this.jm:this.pn("new");break;case this.kz:this.pn("old")}};z.e.zi=function(a,b){a&&this.Xy(b);z.El(this.JI,"display",a?"none":"block");z.El(this.ug,"display",a?"block":"none")};
z.e.Xy=function(a){var b=this.jm,c=this.pn,d=z.X.get(z.X.g.Gt);4===a&&(b=this.kt,c=this.fE,d=z.X.get(z.X.g.WJ));this.ug.innerHTML=d;this.q().re(this.ug,"click",(0,z.r)(function(a){a.stopPropagation();this.zi(!1);yL(this,b);c.apply(this)},this))};z.e.Un=function(a){a.stopPropagation();this.zi(!1);yL(this,this.jm);this.pn()};z.e.Fr=function(a){var b=a.Wb;z.lb(a,{Wb:(0,z.r)(function(){b();this.zi(!0,4)},this)})};
z.e.pn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Wb:(0,z.r)(this.Dd,this)})};z.e.fE=function(){this.dispatchEvent({type:"sortHotThreads",Wb:(0,z.r)(this.Dd,this)})};z.e.tF=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.Ed(z.E.get(b.W)),a.wj(!b),a=b?z.X.get(z.X.g.Xt):z.X.get(z.X.g.Yt),this.ll.innerHTML=a):z.Sh(this.d.Jc,(0,z.r)(this.tF,this))};
z.e.Yn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.Fd()||z.E.get(c.Td);this.ll&&(b?z.N(this.ll,!1):(a=a.Ed(z.E.id)?z.X.get(z.X.g.Yt):z.X.get(z.X.g.Xt),this.ll.innerHTML=a,z.N(this.ll,!0)))};z.e.h=function(){wL.b.h.call(this);z.E.off(null,null,this)};z.u(zL,wL);zL.prototype.K=function(a){this.c=a;z.ro(a,rL,this.s());this.jm=this.n("fyre-stream-sort-newest");this.kz=this.n("fyre-stream-sort-oldest");this.JI=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.Dd()};zL.prototype.pn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.xX.stream,direction:a,Wb:(0,z.r)(this.Dd,this)})};
zL.prototype.s=function(){return{j:{$N:z.X.get(z.X.g.RJ),Rx:z.X.get(z.X.g.Rp),Sx:z.X.get(z.X.g.Sp),Po:z.X.get(z.X.g.aC),fp:z.X.get(z.X.g.Xp)}}};z.u(AL,z.Rx);z.e=AL.prototype;z.e.dn=function(a){this.clear();z.N(this.c,!0);this.kd=a};z.e.clear=function(){this.hd.Ld();this.zb={};this.Dj=[];for(this.nh=this.Qk=null;this.ma&&0!=this.ma.length;)this.Ho(0).p()};z.e.K=function(a){AL.b.K.call(this,a);z.ro(this.c,z.ar,this.s());this.gk=this.n("fyre-stream-content");this.Ai=this.n("fyre-stream-more");this.Ga.S(this.Ai);z.N(this.Ai,!1)};z.e.h=function(){this.Ga&&this.Ga.p();this.Ga=null;AL.b.h.call(this)};
z.e.m=function(){AL.b.m.call(this);this.q().e(this.Ga,"showMore",this.Qw)};z.e.Uv=function(){return this.D.J.xG};z.e.s=function(){return{Zd:z.v.L.mb,kv:!!this.Ga,j:{cz:z.X.get(z.X.g.SJ)}}};z.e.Rw=function(){this.Ga.ft();this.Zg=!0};z.e.jy=function(){this.dispatchEvent({type:this.hu,direction:this.kd,target:this,ZX:this.Zg&&this.EI,Wb:(0,z.r)(this.Rw,this),vj:(0,z.r)(this.UF,this)});this.Zg&&(this.EI=!1)};z.e.qy=function(a){this.Zg||AL.b.qy.call(this,a)};
z.e.Vo=function(){var a=this.D.Lb.Nk,b=this.kd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.yp),c=!b&&a.Zk>-c;b&&-1>a.Zk||c?this.Ga.show():this.Ga.qb()};z.e.start=function(){this.Zg||this.jy()};z.u(BL,z.cG);var PL=z.X.g,QL={};QL.comment=[PL.Km,PL.Qf,PL.ym];QL.liveblog=[PL.oM,PL.AL,PL.eB];BL.prototype.QE=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.l.Fd()?"liveblog":"comment",c=QL[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.aG[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.wa(c,a)};z.u(CL,z.fu);CL.prototype.Yo=200;CL.prototype.Rh=function(){return new DL(this.Ic)};CL.prototype.s=function(){var a={};a.message=this.Gz;return a};z.u(DL,z.$t);DL.prototype.Oc=function(a,b,c){var d=z.cm(this.element),d=new z.Ch(d.width,d.height+25);b=z.Vt(this.element,this.Eh,a,b,d,c,9);z.Kl(a.lastChild,0);b&&(d=new z.Ch(0,-5),z.Vt(this.element,2,a,1,d,c,5),z.Kl(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.u(EL,z.T);z.e=EL.prototype;z.e.r=function(){this.c=z.uo(qL,this.s())};z.e.m=function(){EL.b.m.call(this);this.Va=new CL(this.c,this.l.get("displayName"));this.q().e(this.c,"click",this.hb)};z.e.h=function(){EL.b.h.call(this);this.Va&&this.Va.p()};z.e.s=function(){var a=z.Xd,b={};b.wd=this.l.get(a.wb);b.$b=this.l.get(a.uk);b.aa=this.l.get(a.ua);b.id=this.l.id;b.CT=this.l.id.replace(/[@.]/g,"-");b.Ea=this.l.get(a.Yb);return b};
z.e.hb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.l,type:"author_click"})};z.u(FL,z.T);z.e=FL.prototype;z.e.iB=10;z.e.h=function(){FL.b.h.call(this);delete this.Ac};z.e.Q=function(){FL.b.Q.call(this);this.Ac.off(null,null,this)};z.e.dF=function(a){a=new EL(a);var b=this.Mc();if(b===this.iB){var c=this.Ho(b-1);c&&(c.p(),b--)}0<b?this.De(a,0,!0):this.F(a,!0)};z.e.HS=function(a){var b;this.Tc(function(c){a.id===c.l.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Vn=function(){this.Ac.on(this.Ac.xa.Et,this.dF,this);this.Ac.on(this.Ac.xa.eu,this.HS,this);var a=this.Ac.rb.reverse().slice(0,this.iB);z.w(a,this.dF,this)};z.u(GL,FL);z.u(IL,z.nG);
IL.prototype.ZH=function(a,b){if(!this.Ka){this.w=b;var c=b.get(z.U.wh),d=b.get(z.U.Vd);this.yt=new z.kG(c,d,a.J.Sa);this.F(this.yt);this.Dq=new BL(a.u.v());this.F(this.Dq);this.rs=null;b.io()&&(this.Du=new zL(a),this.F(this.Du),this.Ok=new AL(a),this.F(this.Ok),oL(this.Du,{stream:this.Ok}));this.kh=new wL(a);this.F(this.kh);this.js((0,z.r)(function(a){this.ac=a;this.F(this.ac);a=this.ac;this.Y&&a&&a.S(this.ge,!0)},this));b.get(z.U.Em)&&!z.eg&&this.w.$q()&&(this.w.$g()||this.w.Fd()||this.ww())}};
IL.prototype.s=function(){var a=!this.d.J.sq&&!z.v.iv&&!this.d.J.bE;return{hJ:z.v.L.Hz,iJ:(0,window.encodeURIComponent)(String(window.location.href)),Sa:this.d.J.Sa,$g:this.w.$g(),Fd:this.w.Fd(),oe:z.eg,sv:a,UT:this.d.J.sq,io:this.w.io()}};z.fy={vY:"fyre-archive-stream",wY:"fyre-archive-stream-header",k1:"fyre-top-content-stream",D1:"fyre-widget",Em:"fyre-featured-content-wrapper"};z.lb(z.fy,z.YJ);z.e=IL.prototype;
z.e.r=function(){this.c=z.uo(pL,this.s());var a=this.w.get(z.U.Wi);if(1!==a){var b=this.d.Ib,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.fz(b,a,c,this)}this.Nr.S(this.n(z.fy.lL));this.Ok&&(b=this.n("fyre-archive-stream-header"),this.Du.S(b),this.Ok.S(this.n("fyre-archive-stream")));this.Fh(1);this.ge=this.n(z.fy.th);b=JL(this);z.N(this.ge,b)};
z.e.m=function(){IL.b.m.call(this);var a=this.ac;this.Y&&a&&a.S(this.ge,!0);this.d.U.hp("stream_data_received",this.FR,this);this.q().e(this,"request_content_context",this.dR).e(this,"request_content_reply",this.KS);this.Ok&&this.Ok.start()};z.e.Vn=function(){this.zn&&this.zn.Vn()};z.e.FR=function(){var a=this.w,b=a.get(z.U.yk);z.th||b||(b=(0,z.r)(function(){this.rs=new z.RL(this.d,a.get(z.U.Vd));this.F(this.rs,!0)},this),z.vc(z.v.L.mb+z.v.Cf.rs,null,null,b))};
z.e.ww=function(){var a=new z.UE(this.JG,this);a.zH=(0,z.r)(this.vW,this);var b=(0,z.r)(function(){a.start(0,2E3)},this);z.vc(z.v.L.mb+z.v.Cf.MP,null,null,b)};z.e.vW=function(){var a=this.n("fyre-featured-content-wrapper");this.Fv=new z.nK(this.d);this.F(this.Fv);this.Fv.S(a);this.Fv.Yg()};z.e.js=function(a){if(!this.d.J.readOnly){var b=this.d.u.v();z.Uw(z.Rw.C(),"main",a,{D:this.d,ri:"new"},b);z.E.on(z.E.jc(z.E.k.W),this.Uc,this)}};z.e.Uc=function(){if(this.ge){var a=JL(this);z.N(this.ge,a)}};
z.e.Wh=function(){0<z.Ap(this,this.ac)&&(this.removeChild(this.ac),this.ac.p());this.js((0,z.r)(function(a){this.ac=a;this.F(this.ac);a=this.ac;this.Y&&a&&a.S(this.ge,!0);z.N(this.ge,!0)},this))};z.e.Xg=function(a,b){null!=a&&(this.d.Ib.rl(1),(0,window.setTimeout)((0,z.r)(function(){var c=b&&function(a){z.Qw(a.nb)};this.Ka||z.oG(this,a,c)},this),3E3))};z.e.dR=function(a){z.oG(this,a.Uk)};z.e.KS=function(a){z.oG(this,a.Uk,function(a){z.Qw(a.nb)})};
z.e.h=function(){IL.b.h.call(this);z.E.off(z.E.jc(z.E.k.W),this.Uc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.u(KL,z.xz);z.e=KL.prototype;z.e.ke=function(a,b){KL.b.ke.call(this,a,b);a.e(b,"repliesExpanded",this.qF);a.e(b,"sortHotThreads",this.US);a.e(b,"sortOrderChanged",this.XF);a.e(b,"sortTopComments",this.VS);a.e(b,"archiveShowMore",this.NQ);a.e(b,"archiveSortOrderChanged",this.OQ)};
z.e.NQ=function(a){var b=a.Wb||z.n,c=(0,z.r)(this.Oe,this,a.target),d=this.d.Lb;a=a.ZX;d.Nk||(d.Nk=new nL(d.D));d=d.Nk;a=a?d.Zk:mL(d);var f=d.Zc[a];f&&(d.Zk=a);if(f)b(),c(f);else{d=this.d.Lb.ml();a=d.k.kf;if(d.get(a))b();else d.on(d.jc(a),b,this);z.yz(this,d,c)}};z.e.qw=function(a,b){var c=2===b.$c,d=1!==b.$c;switch(b.type){case 0:var f=this.d.u.v(),f=z.Om(b,f),g=f.get(z.cn),g=this.d.u.$a().get(g);f.set(z.Rm,g);a.Iw(f,c,d)}};
z.e.OF=function(a){if(1!==this.Qm){var b=this.pX.kh;b.zi(!1);yL(b,b.jm);z.lb(a,{direction:"new",Wb:z.n});this.XF(a)}};z.e.OQ=function(a){z.zz(this);a.stream.dn(a.direction);var b=this.d.Lb.ml(a.direction,!0),c=(0,z.r)(function(b){a.Wb();this.Oe(a.stream,b)},this);z.yz(this,b,c,a.vj)};z.e.XF=function(a){this.d.J.ai=null;var b=z.Bz(this,1);z.lw(this.d.Lb);b.dn(a.direction);var c=z.kw(this.d.Lb,a.direction),d=(0,z.r)(function(c){a.Wb();this.Oe(b,c)},this);z.yz(this,c,d,a.vj)};
z.e.VS=function(a){var b=z.Bz(this,3),c=this.d.Lb.Lh("likes");z.yz(this,c,(0,z.r)(function(c){a.Wb();z.hb(c)?z.Qx(b):this.Oe(b,c)},this))};z.e.US=function(a){var b=z.Bz(this,4),c=this.d.Lb.Ph();z.yz(this,c,(0,z.r)(function(c){a.Wb();z.hb(c)?z.Qx(b):this.Oe(b,c)},this))};z.u(LL,z.Ts);z.e=LL.prototype;z.e.c=null;z.e.h=function(){LL.b.h.call(this);this.mt.p();this.uD.p();this.Rb.Y&&this.Rb.p();this.Of&&this.Of.p();delete this.Of};z.e.Bl=function(a){LL.b.Bl.call(this,a);this.mt=new KL(this.d);this.mt.handle(a);this.uD=new z.uz(this.d);this.uD.handle(a)};z.e.tz=function(){this.d.Ci.stop()};z.e.wX=function(){this.d.Ll.stop()};z.e.dk=function(){this.d.Ci.start()};z.e.tX=function(){this.d.Ll.start()};
z.e.pa=function(){this.Of&&this.Of.p();this.Rb.pa(this.c);var a=z.Vs(window.location,"reply_editor");if("object"===typeof window.Livefyre&&window.Livefyre.MN)z.Zs(this,a);else{var b=z.Ws(this);this.Rb.Xg(b,a)}this.d.U.N("render_complete",this.c)};z.u(ML,z.Pn);ML.prototype.PC=tL.C();ML.prototype.h=function(){ML.b.h.call(this);this.stop();delete this.J;delete this.ha;NL(this);z.Un(this);this.uj&&(this.uj.p(),delete this.uj)};ML.prototype.Bz=function(){this.stop();NL(this);ML.b.Bz.call(this)};z.mg.main.Hh.ka(ML);})(fyre.conv);
