<div class="main-pull-down-menu">
<ul id="nav">


<li><a href='/'>Home</a></li>


<li><a href='#'>Writing</a><ul>
<li><a href='http://www.rajiv.com/cloud-computing-book/'>Upcoming Book: Cloud Computing</a></li>
<li><a href='/blog/category/management/'>Leadership &amp; Management</a></li>
<li><a href='/blog/category/technology/'>Computing &amp; Technology</a></li>
<li><a href='/blog/category/philosophy/'>Philosophy</a></li>
<li><a href='/blog/' rel="me">All Blog Posts</a></li>
</ul></li>


<li><a href='#'>Professional</a><ul>
<li><a href='/resume/' rel="me">Resume &amp; References</a></li>
<li><a href='/resume/awards/' rel="me">Awards</a></li>
<li><a href='/biography/' rel="me">Biography</a></li>
<li><a href='/work/com/'>Research &amp; Development</a></li>
<li><a href='/work/free/'>Free Software</a></li>
<li><a href='/work/com/tech.htm'>Projects</a></li>
</ul></li>


<li><a href='#'>Personal</a><ul>
<li><a href='/blog/category/personal-life' rel="me">Posts on Personal Life</a></li>
<li><a href='http://photos.rajiv.com/' rel="me">Photo Albums</a></li>
<li><a href='/videos/' rel="me">Videos</a></li>
<li><a href='/personal/' rel="me">Personal Info</a></li>
<li><a href='/friends/' rel="me">Friends &amp; Social Networks</a></li>
<li><a href='/charity/'>Charity &amp; Social Work</a></li>
</ul></li>


<li><a href='#'>About</a><ul>
<li><a href='/contact/' rel="me">Contact</a></li>
<li><a href='/advertise/'>Advertise</a></li>
<li><a href='/readme/'>readme: Terms of Use &amp; Privacy</a></li>
<li><a href='/archive/'>Archive of Parts of This Site</a></li>
</ul></li>


<li><a href='#'>Welcome</a><ul>
<li><a href='/wordpress/wp-login.php'>Log In</a></li>
<li><a href='/wordpress/wp-login.php?action=logout'>Log Out</a></li>
<li><a href='/wordpress/wp-login.php?action=register'>Register</a></li>
</ul></li>


<li><form action="http://www.rajiv.com/search/" id="cse-search-box">
  <div>
    <input type="hidden" name="cx" value="partner-pub-9066662519925137:o2yp8s-cpzr" />
    <input type="hidden" name="cof" value="FORID:10" />
    <input type="hidden" name="ie" value="ISO-8859-1" />
    <input type="text" name="q" size="31" />
    <input type="submit" name="sa" value="Search" />
  </div>
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&amp;lang=en"></script></li>


<li><a href='#'>Related Sites</a><ul>
<li><a href="http://www.rajiv.com/">Web Site of Rajiv Pant</a>
<li><a href='http://www.revolutioncloud.com/'>Revolution Cloud Book</a></li>
<li><a href='http://www.listswiki.com/'>Wiki of Checklists</a></li>
<li><a href='http://www.cofax.org/'>Cofax: Open Source CMS</a></li>
<li><a href='http://www.effectuation.net//'>My Former Company: Effectuation</a></li>
<li><a href='http://comedy.rajiv.com/'>Comedy From India</a></li>
<li><a href='http://comedy.rajiv.com/india/info/'>India: Some Useful Info</a></li>
<li><a href='http://spv.rajiv.com/'>Sardar Patel Vidyalaya Alumni</a></li>
</ul></li>

</ul>
</div>
