

<li><a href='#'>Related Sites</a><ul>
<li><a href="http://www.rajiv.com/">Web Site of Rajiv Pant</a>
<li><a href='http://www.revolutioncloud.com/'>Revolution Cloud Book</a></li>
<li><a href='http://www.listswiki.com/'>Wiki of Checklists</a></li>
<li><a href='http://www.cofax.org/'>Cofax: Open Source CMS</a></li>
<li><a href='http://www.effectuation.net//'>My Former Company: Effectuation</a></li>
<li><a href='http://comedy.rajiv.com/'>Comedy From India</a></li>
<li><a href='http://comedy.rajiv.com/india/info/'>India: Some Useful Info</a></li>
<li><a href='http://spv.rajiv.com/'>Sardar Patel Vidyalaya Alumni</a></li>
</ul></li>


